cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

peerDependencyRules:
  allowedVersions:
    '@vue/composition-api>vue': '>= 2.5'

packages:
  - 'packages/**'
  - 'examples/angular/**'
  - 'examples/react/**'
  - 'examples/solid/**'
  - 'examples/vue/**'
  - 'examples/svelte/**'
  - 'examples/preact/**'
