cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

peerDependencyRules:
  allowedVersions:
    '@vue/composition-api>vue': '>= 2.5'

packages:
  - 'packages/**'
  - 'examples/angular/**'
  - 'examples/react/**'
  - 'examples/solid/**'
  - 'examples/vue/**'
  - 'examples/svelte/**'
  - 'examples/preact/**'
  - 'examples/lit/**'

allowBuilds:
  # root dependency
  nx: true
  unrs-resolver: false # not directly required for build (could enable for better build perf)
  esbuild: true

  # @angular/build
  '@parcel/watcher': false # optional dep of @angular/build
  lmdb: false # optional dep of @angular/build
  msgpackr-extract: false # optional dep of @angular/build

  # @tanstack/vue-store
  vue-demi: true # only required for vue 2 support
