/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as Run from "@marko/run";


declare module "@marko/run" {
	interface AppData extends Run.DefineApp<{
		routes: {
			"/": { verb: "get"; };
			"/client-only-first-paint": { verb: "get"; };
			"/context": { verb: "get"; };
			"/context-above": { verb: "get"; };
			"/context-multi": { verb: "get"; };
			"/context-perreq": { verb: "get"; };
			"/dup-try": { verb: "get"; };
			"/effect-order": { verb: "get"; };
			"/gate-render-only": { verb: "get"; };
			"/liveness": { verb: "get"; };
			"/multi": { verb: "get"; };
			"/ooo": { verb: "get"; };
			"/outside": { verb: "get"; };
			"/payload": { verb: "get"; };
			"/provider-collision": { verb: "get"; };
			"/streaming-fill-onmount": { verb: "get"; };
			"/streaming-fill-render": { verb: "get"; };
			"/streaming-liveness": { verb: "get"; };
			"/streaming-out-of-order": { verb: "get"; };
		}
	}> {}
}

declare module "../src/routes/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/client-only-first-paint/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/client-only-first-paint"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/context/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/context"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/context-above/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/context-above"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/context-multi/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/context-multi"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/context-perreq/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/context-perreq"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/dup-try/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/dup-try"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/effect-order/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/effect-order"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/gate-render-only/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/gate-render-only"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/liveness/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/liveness"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/multi/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/multi"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/ooo/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/ooo"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/outside/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/outside"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/payload/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/payload"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/provider-collision/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/provider-collision"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/streaming-fill-onmount/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/streaming-fill-onmount"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/streaming-fill-render/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/streaming-fill-render"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/streaming-liveness/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/streaming-liveness"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/streaming-out-of-order/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/streaming-out-of-order"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}
